spring:
  application:
    name: eureka-client
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5437/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    generate-ddl: false
    open-in-view: false
    show-sql: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defoultZone: http://localhost:8082/eureka-server

