spring:
  application:
    name: eureka-server
server:
  port: 8082

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defoultZone: http://localhost:8082/eureka-server

